version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: oms-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka-native:latest
    container_name: oms-kafka
    ports:
      - "9092:9092"

volumes:
  postgres-data: